### ISSUE TITLE
single letter flags could be more friendly

### ISSUE THREAD

**Issue by rogpeppe** [myitcv/gobin#28]
I find it hard to remember if `-g` is "global" or "get", and `gobin -r somemodule` would probably be more obvious as `gobin -run somemodule`.
Perhaps consider `-run` and `-get`, etc.

**Comment by myitcv** [comment]
Thanks - yes, sounds like a sensible change to make

**Comment by myitcv** [comment]
Adding a note here on our discussion regarding `-g` vs `-u` as a reminder:

> `-u` still seems like it might be a reasonable spelling (and the consistency with `go get` is a big plus if we're wanting this to be rolled into the go tool at some point)
