### ISSUE TITLE
Proposal: run with command name only

### ISSUE THREAD

**Issue by bcomnes** [myitcv/gobin#68]
Really enjoying the gobin + tools.go workflow!  One nice feature of a similar tool called gex is that it allows you to `gex run bar` where `bar` was installed from `github.com/foo/bar` for example.  

It would be nice if `gobin` also supported this kind of feature.  Instead of  `gobin -m -run golang.org/x/tools/cmd/stringer -help` you could just run `gobin -m -run stringer -help` and whatever version you have defined in your tools.go/go.mod is run. 

Perhaps a `.gobincache/bin` full of your modules symlinked bins, and supplementing the `gobin -m -run` would be one way to implement shortname discoverability.

**Comment by myitcv** [comment]
_Apologies again for the delay in replying, I had closed [Octobox](https://octobox.io/) and so was not receiving notifications for this repo._

I fully understand what you're getting at here. For example, I have a number of aliases setup in bash of the sort:

```
alias main='gobin -run example.com/main'
```

Furthermore, within certain local module repositories I have aliases set by [`smartcd`](https://github.com/cxreg/smartcd/) of the sort:

```
autostash alias gg='gobin -m -run myitcv.io/cmd/gg'
```

Therefore, my knee jerk response to this right now would be "no" for two reasons:

* it's entirely possible and (indeed much more configurable) to define aliases in your shell
* this sort of approach is susceptible to collisions and I think the user is better placed to manage those potential collisions

But please, I'm open to other opinions on this. Having a good example/precedent here would help, and maybe just spelling that out in more detail would be helpful for the discussion.

cc @rogpeppe and @mvdan for other thoughts

**Comment by bcomnes** [comment]
Those are good points, and I'm weighing if less moving parts is better for reliably in the long run.  I would like to see some of the capabilities of gobin (as it is now) make it into the actual go tool someday, and you seem more in tune with what constraints could help make that happen. 

After using gobin a bit more, I find myself using it in two places:

- Make file steps
- go Generate comments

While it does make for much longer commands (having to type out `GitHub.com/user/name/wahtever-else`) it avoids the collision problem all together, which, as time goes on, avoiding problems altogether seems better to error on than complicating life for the sake of convince.  

As for your alias + autocd suggestion,  yes that works, but I don't like that solution for these reasons:

- `autocd` an additional global dependency.  We can safely assume most people working on a go project have go installed properly (e.g. GOPATH/bin is in their path so go get works).  It's also highly likely they have Make installed.  It's much less likely they have `autocd` installed. 
- `autocd` or an activation script requires contributors to modify their shell environment or session.  I hate when projects make me do this, and I want to avoid doing this to others.  Projects should be well contained.
- It's an environment activation strategy.  While popular in python and some go projects (e.g. 'please set your GOPATH to this non-default location', annoyingly imo), many tooling ecosystems have opted for context aware tooling (e.g. npm, cargo, git) that doesn't require the modification of the entire shell session just to properly work on it, be it automated or manual.  I would argue go modules moving away from requiring development the GOPATH is a step in this context aware direction instead of environment modifications.

I'm going to close this for now.   While I would enjoy the addition of this, lets error on the side of simplicity.
