### ISSUE TITLE
Why not use `go run github.com/my/package`?

### ISSUE THREAD

**Issue by vektah** [myitcv/gobin#71]
As of go 1.11 we can `go run github.com/some/main/package` directly, and it will be fetched, locked, built, cached and run. This is what I've been encouraging to use in go generate stanzas.

What does this tool offer over that? Might be worth adding to your faq?

**Comment by vektah** [comment]
And reading more carefully I see
> golang/go/issues/#25416 concludes that go run intentionally re-runs the link step and does not cache the resulting binary, which means go run X is going to be (much) slower than simply running an installed binary.

**Comment by myitcv** [comment]
👍 - for this reason I use `gobin -m -run` in all of my `go:generate` directives.
